spring:
  application:
    name: adg-rule
  profiles:
    active: prod  #切换至 dev 即可输出调试信息

logging:
  file:
    path: ./logs

application:
  config:
    expected_quantity: 2000000  #预期规则数量
    fault_tolerance: 0.001 #容错率
    warn_limit: 7 #警告阈值, 规则长度小于该值时会输出警告日志
    batch_size: 10000 #写入文件的批次大小

  # 规则源配置，remote为远程规则，local为本地规则，支持多个规则源
  rule:

    # 仅支持 http/https，不限定响应内容格式
    remote:
      - name: 'GOODBYEADS' #规则名称
        path: 'https://raw.githubusercontent.com/8680/GOODBYEADS/master/rules.txt' #规则地址
      - name: 'GOODBYEADS' #规则名称
        path: 'https://adrules.top/dns.txt' #规则地址
      - name: 'GOODBYEADS' #规则名称
        path: 'https://anti-ad.net/easylist.txt' #规则地址   
      - name: 'GOODBYEADS' #规则名称
        path: 'https://github.com/Potterli20/file/releases/download/github-hosts/Accelerate-Hosts.txt' #规则地址
      - name: 'GOODBYEADS' #规则名称
        path: 'https://raw.githubusercontent.com/TG-Twilight/AWAvenue-Ads-Rule/main/AWAvenue-Ads-Rule.txt' #规则地址
      - name: 'GOODBYEADS' #规则名称
        path: 'https://raw.githubusercontent.com/lingeringsound/10007_auto/master/reward' #规则地址
      - name: 'GOODBYEADS' #规则名称
        path: 'https://raw.githubusercontent.com/5whys-adblock/AdGuardHome-rules/main/rules/output_full.txt' #规则地址   
      - name: 'GOODBYEADS' #规则名称
        path: 'https://raw.githubusercontent.com/217heidai/adblockfilters/main/rules/adblockdns.txt' #规则地址
    #本地规则请将文件放置到项目路径rule目录中
    local:
      - name: 'local rule'
        path: 'local-rule.txt'
  output:
    file_header: |  #输出文件头, 占位符${name}将被替换为文件名，如all.txt,  ${date} 将被替换为当前日期
      [关圣®云去广告DNS 去广告规则列表]
      ! Title: ${name}
      ! Last Modified: ${date}
      ! Homepage: https://github.com/guandasheng/TheBestAdrules/
    path: rule   #规则文件输出路径，相对路径默认从 项目目录开始
    files:
      all.txt: #输出文件名
        - DOMAIN  #域名规则，仅完整域名
        - REGEX   #正则规则，包含正则的域名规则，AdGH支持
        - MODIFY  #修饰规则，添加了一些修饰符号的规则，AdG支持
        - HOSTS   #Hosts规则
      dns.txt:
        - DOMAIN
        - REGEX
        - HOSTS
      hosts.txt:
        - HOSTS
      regex.txt:
        - REGEX
      domain.txt:
        - DOMAIN
      modify.txt:
        - MODIFY
